#!/usr/bin/env bash
# This script:
#   creates a file /var/run/myscript.pid containing the its PID.
#   displays "To infinity and beyond" indefinitely
#   displays "I hate the kill command" on receiving a SIGTERM
#   displays "Y U no love me?!" on receiving a SIGINT
#   deletes the file /var/run/myscript.pid and terminates on
#+  receiving a SIGQUIT or SIGTERM.

terminator() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUIT
done
