#!/usr/bin/env bash
# Displays numbers from 1 to 20. Also:
#   "bad luck from China" on the 4th iteration
#   "bad luck from Japan" on the 9th iteration
#   "bad luck from Italy" on the 17th iteration

i=1

while [ $i -le 20 ]
do
  echo "$i"
  case $i in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( i++ ))
done
